/// ENGLISH ///
export const en = {
  hi: "Hello!",
  iAm: "I am XBot, your virtual assistant.",
  letUsBegin: "Let us begin",
  choose: "Choose a subscription",
  skip: "Skip",
  weeklyPlan: "Weekly Plan",
  monthlyPlan: "Monthly Plan",
  anualPlan: "Anual Plan",
  unlimitedAccess: "Unlimited messages to the virtual assistant XBot",
  technicalSupport: "Priority technical support",
  versions: "Regular app updates",
  question: "Ask me...",
  version: "Version",
  myPlan: "My plan",
  share: "Share XBot",
  review: "Leave a review",
  presentation: "XBot offers you a personalized virtual assistant to help you with your questions and doubts at any time of the day. It's easy to use, and the bot learns from every conversation to deliver accurate and effective responses over time.",
  limitTitle: "Limit reached",
  limitText: "You have reached your daily limit of messages",
  noInternet: "You don't have internet connection",
  upgrade: "Upgrade",
  errorMessage: "Sorry, I am not able to respond at the moment.",
  restorePurchases: "Restore Purchases",
  error: "Error",
  success: "Success",
  purchasesRestored: "Your purchases has been restored",
  noRestored: "No purchases to restore",
  privacityPolicy: "Privacy Policies",
  termsConditions: "Terms and conditions",
  continue: "By continuing, you agree to our",
  settings: "Settings",
  actualPlan: "Your actual plan: ",
  noMoreMessages: "You don't have any more messages, don't worry tomorrow you will have 10 more. Upgrade your plan and you can have unlimited messages",
  haveMessages: "You can send the bot {messageCount} messages. If you want to have unlimited messages, upgrade your plan",
  model: "Model: ",
  clearConversationTitle: "Clear Conversation",
  clearConversationText: "Are you sure you want to clear the conversation?",
  cancel: "Cancel",
  confirm: "Confirm"
}

/// CASTELLANO ///
export const es = {
  hi: "¡Hola!",
  iAm: "Soy XBot, tu asistente virtual.",
  letUsBegin: "Empecemos",
  choose: "Elige una suscripción",
  skip: "Saltar",
  weeklyPlan: "Plan Semanal",
  monthlyPlan: "Plan Mensual",
  anualPlan: "Plan Anual",
  unlimitedAccess: "Mensajes ilimitados al asistente virtual XBot",
  technicalSupport: "Soporte técnico prioritario",
  versions: "Actualizaciones periódicas de la aplicación",
  question: "Pregúntame...",
  version: "Versión",
  myPlan: "Opciones de planes",
  share: "Compartir XBot",
  review: "Dejar una reseña",
  presentation: "XBot te ofrece un asistente virtual personalizado para ayudarte con tus preguntas y dudas en cualquier momento del día. Es fácil de usar y el bot aprende de cada conversación para ofrecer respuestas precisas y efectivas con el tiempo.",
  limitTitle: "Límite alcanzado",
  limitText: "Ha alcanzado su límite diario de mensajes",
  noInternet: "No tienes conexion a internet",
  upgrade: "Mejorar",
  errorMessage: "Lo siento, ahora mismo no puedo responderte.",
  restorePurchases: "Restaurar las compras",
  error: "Error",
  success: "Éxito",
  purchasesRestored: "Tus compras han estado restablecidas",
  noRestored: "No hay ninguna compra para restablecer",
  privacityPolicy: "Políticas de privacidad",
  termsConditions: "Términos y condiciones",
  continue: "Al continuar, aceptas nuestras",
  settings: "Ajustes",
  actualPlan: "Tu plan actual: ",
  noMoreMessages: "No tienes más mensajes, no te preocupes mañana tendrás 10 más. Mejora tu plan y podrás tener mensajes ilimitados",
  haveMessages: "Puedes enviar al bot {messageCount} mensajes. Si quieres tener mensajes ilimitados mejora tu plan",
  model: "Modelo: ",
  clearConversationTitle: "Borrar conversación",
  clearConversationText: "¿Estás seguro de que quieres borrar la conversación?",
  cancel: "Cancelar",
  confirm: "Confirmar"
}

/// CATALÀ ///
export const ca = {
  hi: "Hola!",
  iAm: "Sóc XBot, el teu assistent virtual.",
  letUsBegin: "Comencem",
  choose: "Trieu una subscripció",
  skip: "Saltar",
  weeklyPlan: "Pla Semanal",
  monthlyPlan: "Pla Mensual",
  anualPlan: "Pla Anual",
  unlimitedAccess: "Missatges il·limitat a l'assistent virtual XBot",
  technicalSupport: "Suport tècnic prioritari",
  versions: "Actualitzacions periòdiques de l'aplicació",
  question: "Pregunta'm...",
  version: "Versió",
  myPlan: "Opcions de plans",
  share: "Compartir XBot",
  review: "Deixar una ressenya",
  presentation: "XBot us ofereix un assistent virtual personalitzat per ajudar-vos amb les vostres preguntes i dubtes en qualsevol moment del dia. És fàcil dutilitzar i el bot aprèn de cada conversa per oferir respostes precises i efectives amb el temps.",
  limitTitle: "S'ha arribat al límit",
  limitText: "Heu assolit el vostre límit diari de missatges",
  noInternet: "No tens connexió a internet",
  upgrade: "Millorar",
  errorMessage: "Ho sento, ara mateix no et puc respondre.",
  restorePurchases: "Restablir les compres",
  error: "Error",
  success: "Èxit",
  purchasesRestored: "Les teves compres han estat restablertes",
  noRestored: "No hi ha cap compra per restablir",
  privacityPolicy: "Polítiques de privacitat",
  termsConditions: "Termes i condicions",
  continue: "Al continuar, aceptes les nostres",
  settings: "Configuració",
  actualPlan: "El teu pla actual: ",
  noMoreMessages: "No tens més missatges, no pateixis demà en tindràs 10 més. Millora el teu pla i podràs tenir missatges il·limitats",
  haveMessages: "Pots enviar al bot {messageCount} missatges. Si vols tenir missatges il·limitats millora el teu pla",
  model: "Model: ",
  clearConversationTitle: "Esborrar conversa",
  clearConversationText: "Estàs segur que vols esborrar la conversa?",
  cancel: "Cancel·lar",
  confirm: "Confirmar"
}
